export enum AuditAction {
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",

    ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED",

    ROLE_CHANGED = "ROLE_CHANGED",

    USER_CREATED = "USER_CREATED",
    USER_UPDATED = "USER_UPDATED",
 

    USER_ADDED_TO_TEAM = "USER_ADDED_TO_TEAM",
    USER_REMOVED_FROM_TEAM = "USER_REMOVED_FROM_TEAM",
}

export enum AuditEntityType {
    AUTH = "AUTH",
    ORGANIZATION = "ORGANIZATION",
    USER = "USER",
    TEAM = "TEAM",
    INCIDENT = "INCIDENT",
    TASK = "TASK",
}