export enum TimelineEventType {
    INCIDENT_CREATED = "INCIDENT_CREATED",
    INCIDENT_STATUS_CHANGED = "INCIDENT_STATUS_CHANGED",
    INCIDENT_UPDATED = "INCIDENT_UPDATED",
    INCIDENT_TEAM_ASSIGNED = "INCIDENT_TEAM_ASSIGNED",

    TASK_CREATED = "TASK_CREATED",
    TASK_ASSIGNED = "TASK_ASSIGNED",
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED",
    TASK_COMPLETED = "TASK_COMPLETED",
    TASK_UPDATED = "TASK_UPDATED",

    FILE_UPLOADED = "FILE_UPLOADED",
    FILE_DELETED = "FILE_DELETED",

    WAR_ROOM_CREATED = "WAR_ROOM_CREATED",
    WAR_ROOM_JOINED = "WAR_ROOM_JOINED",
    WAR_ROOM_LEFT = "WAR_ROOM_LEFT",
    WAR_ROOM_CLOSED = "WAR_ROOM_CLOSED",

    INCIDENT_CREATED_FROM_ALERT = "INCIDENT_CREATED_FROM_ALERT",
}