import { Container } from "inversify";
import { TYPES } from "../types";

import { IUserRepository } from "@/modules/auth/domain/repositories/IUserRepository";
import { PrismaUserRepository } from "@/modules/auth/infrastructure/repositories/PrismaUserRepository";

import { IOrganizationRepository } from "@/modules/organization/domain/repositories/IOrganizationRepository";
import { PrismaOrganizationRepository } from "@/modules/organization/infrastructure/repositories/PrismaOrganizationRepository";
import { IOrganizationVerificationRepository } from "@/modules/organization/domain/repositories/IOrganizationVerificationRepository";
import { PrismaOrganizationVerificationRepository } from "@/modules/organization/infrastructure/repositories/PrismaOrganizationVerificationRepository";
import { NodemailerOrganizationEmailService } from "@/modules/organization/infrastructure/services/NodemailerOrganizationEmailService";
import { IOrganizationEmailService } from "@/modules/organization/domain/interfaces/IOrganizationEmailService";
import { ITeamRepository } from "@/modules/team-management/domain/interfaces/ITeamRepository";
import { PrismaTeamRepository } from "@/modules/team-management/infrastructure/repositories/PrismaTeamRepository";
import { ITeamMemberRepository } from "@/modules/team-management/domain/interfaces/ITeamMemberRepository";
import { PrismaTeamMemberRepository } from "@/modules/team-management/infrastructure/repositories/PrismaTeamMemberRepository";
import { ITeamInvitationRepository } from "@/modules/team-management/domain/interfaces/ITeamInvitationRepository";
import { PrismaTeamInvitationRepository } from "@/modules/team-management/infrastructure/repositories/PrismaTeamInvitationRepository";
import { IIncidentRepository } from "@/modules/incident/domain/interfaces/IIncidentRepository";
import { PrismaIncidentRepository } from "@/modules/incident/infrastructure/repositories/PrismaIncidentRepository";
import { ITaskRepository } from "@/modules/task-management/domain/interfaces/ITaskRepository";
import { PrismaTaskRepository } from "@/modules/task-management/infrastructure/repositories/PrismaTaskRepository";
import { IIntegrationRepository } from "@/modules/integration/domain/interfaces/IIntegrationRepository";
import { PrismaIntegrationRepository } from "@/modules/integration/infrastructure/repositories/PrismaIntegrationRepository";
import { PrismaMonitoringProjectRepository } from "@/modules/monitoring/infrastructure/repositories/PrismaMonitoringProjectRepository";
import { IMonitoringProjectRepository } from "@/modules/monitoring/domain/interfaces/IMonitoringProjectRepository";
import { IAlertRepository } from "@/modules/alert/domain/interfaces/IAlertRepository";
import { PrismaAlertRepository } from "@/modules/alert/infrastructure/repositories/PrismaAlertRepository";
import { IAlertRuleRepository } from "@/modules/alertRule/domain/interfaces/IAlertRuleRepository";
import { PrismaAlertRuleRepository } from "@/modules/alertRule/infrastructure/repositories/PrismaAlertRuleRepository";
import { IAlertRoutingRuleRepository } from "@/modules/alertRoutingRule/domain/interfaces/IAlertRoutingRuleRepository";
import { PrismaAlertRoutingRuleRepository } from "@/modules/alertRoutingRule/infrastructure/repositories/PrismaAlertRoutingRuleRepository";
import { IFileRepository } from "@/modules/file-management/domain/interface/IFileRepository";
import { PrismaFileRepository } from "@/modules/file-management/infrasturcture/repositories/PrismaFileRepository";
import { IFileStorage } from "@/modules/file-management/domain/interface/IFileStorage";
import { CloudinaryFileStorage } from "@/modules/file-management/infrasturcture/storage/CloudinaryFileStorage";
import { IWarRoomRepository } from "@/modules/war-room/domain/interface/IWarRoomRepository";
import { PrismaWarRoomRepository } from "@/modules/war-room/infrasturcture/repositories/PrismaWarRoomRepository";
import { IWarRoomParticipantRepository } from "@/modules/war-room/domain/interface/IWarRoomParticipantRepository";
import { PrismaWarRoomParticipantRepository } from "@/modules/war-room/infrasturcture/repositories/PrismaWarRoomParticipantRepository";
import { IWarRoomMessageRepository } from "@/modules/war-room/domain/interface/IWarRoomMessageRepository";
import { PrismaWarRoomMessageRepository } from "@/modules/war-room/infrasturcture/repositories/PrismaWarRoomMessageRepository";
import { ITimelineEventRepository } from "@/modules/timeline/domain/interfaces/ITimelineEventRepository";
import { PrismaTimelineEventRepository } from "@/modules/timeline/infrastructure/repositories/PrismaTimelineEventRepository";
import { IAuditLogRepository } from "@/modules/audit-log/domain/interface/IAuditLogRepository";
import { PrismaAuditLogRepository } from "@/modules/audit-log/infrastructure/repositories/PrismaAuditLogRepository";
import { INotificationRepository } from "@/modules/notification/domain/interface/INotificationRepository";
import { PrismaNotificationRepository } from "@/modules/notification/infrastructure/repositories/PrismaNotificationRepository";
import { IPlanRepository } from "@/modules/plan/domain/interface/IPlanRepository";
import { PrismaPlanRepository } from "@/modules/plan/infrastructure/repositories/PrismaPlanRepository";
import { ISubscriptionRepository } from "@/modules/subscription/domain/interface/ISubscriptionRepository";
import { PrismaSubscriptionRepository } from "@/modules/subscription/infrastructure/repositories/PrismaSubscriptionRepository";

export function bindCore(container: Container) {

    container.bind<IUserRepository>(TYPES.UserRepository).to(PrismaUserRepository).inSingletonScope();
    container.bind<IOrganizationRepository>(TYPES.OrganizationRepository).to(PrismaOrganizationRepository).inSingletonScope();
    container.bind<IOrganizationVerificationRepository>(TYPES.OrganizationVerificationRepository).to(PrismaOrganizationVerificationRepository).inSingletonScope();
    container.bind<IOrganizationEmailService>(TYPES.OrganizationEmailService).to(NodemailerOrganizationEmailService).inSingletonScope();
    container.bind<ITeamRepository>(TYPES.TeamRepository).to(PrismaTeamRepository).inSingletonScope();
    container.bind<ITeamMemberRepository>(TYPES.TeamMemberRepository).to(PrismaTeamMemberRepository).inSingletonScope();
    container.bind<ITeamInvitationRepository>(TYPES.TeamInvitationRepository).to(PrismaTeamInvitationRepository).inSingletonScope();
    container.bind<IIncidentRepository>(TYPES.IncidentRepository).to(PrismaIncidentRepository).inSingletonScope();
    container.bind<ITaskRepository>(TYPES.TaskRepository).to(PrismaTaskRepository).inSingletonScope();
    container.bind<IIntegrationRepository>(TYPES.IntegrationRepository).to(PrismaIntegrationRepository).inSingletonScope();
    container.bind<IMonitoringProjectRepository>(TYPES.MonitoringProjectRepository).to(PrismaMonitoringProjectRepository).inSingletonScope();
    container.bind<IAlertRepository>(TYPES.AlertRepository).to(PrismaAlertRepository).inSingletonScope();
    container.bind<IAlertRuleRepository>(TYPES.AlertRuleRepository).to(PrismaAlertRuleRepository).inSingletonScope();
    container.bind<IAlertRoutingRuleRepository>(TYPES.AlertRoutingRuleRepository).to(PrismaAlertRoutingRuleRepository).inSingletonScope();
    container.bind<IFileRepository>(TYPES.fileRepository).to(PrismaFileRepository).inSingletonScope();
    container.bind<IFileStorage>(TYPES.fileStorage  ).to(CloudinaryFileStorage).inSingletonScope();
    container.bind<IWarRoomRepository>(TYPES.warroomRepository).to(PrismaWarRoomRepository).inSingletonScope();
    container.bind<IWarRoomParticipantRepository>(TYPES.warroomParticipantsRepository).to(PrismaWarRoomParticipantRepository).inSingletonScope();
    container.bind<IWarRoomMessageRepository>(TYPES.warRoomMessageRepository).to(PrismaWarRoomMessageRepository).inSingletonScope();
    container.bind<ITimelineEventRepository>(TYPES.TimeLineRepository).to(PrismaTimelineEventRepository).inSingletonScope();
    container.bind<IAuditLogRepository>(TYPES.AuditlogRepository).to(PrismaAuditLogRepository).inSingletonScope();
    container.bind<INotificationRepository>(TYPES.notificationRepository).to(PrismaNotificationRepository).inSingletonScope();
    container.bind<IPlanRepository>(TYPES.planRepository).to(PrismaPlanRepository).inSingletonScope();
    container.bind<ISubscriptionRepository>(TYPES.subscriptionRepository).to(PrismaSubscriptionRepository).inSingletonScope();

}